apiVersion: v1
kind: Secret
metadata:
  name: smtp-aws-ses
data:
  RELAY_PASSWORD: QVdTTE9HSU5TRUNSRVRLRVk=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-aws-ses
data:
  RELAY_HOST: email-smtp.eu-west-3.amazonaws.com
  RELAY_LOGIN: AWSLOGINHERE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smtp-aws-ses
  name: smtp-aws-ses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp-aws-ses
  template:
    metadata:
      labels:
        app: smtp-aws-ses
    spec:
      containers:
      - image: infrabuilder/smtp-aws-ses
        name: smtp-aws-ses
        envFrom:
        - configMapRef:
            name: smtp-aws-ses
        - secretRef:
            name: smtp-aws-ses
        ports:
        - containerPort: 25
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: smtp-aws-ses
  name: smtp-aws-ses
spec:
  ports:
  - name: smtp
    port: 25
    protocol: TCP
    targetPort: 25
  selector:
    app: smtp-aws-ses
  type: ClusterIP
